<?php 
$user_email_instructions = 'Thank you for reporting a found pet to Indy Lost Pet Alert! We will soon post the pet on our website, Facebook page and Twitter.

<strong><u>A few tips regarding the found pet:</u></strong>
<ul>
 	<li><strong>Have the pet scanned for a microchip.</strong> This is a free service offered by all vets and shelters. In Marion County, this is a requirement <strong>within 48 hours of finding a pet</strong> (or surrender it to Indianapolis Animal Care Services at 2600 S. Harding St. Indy). *IF you need a volunteer to come and scan the pet, please let us know!</li>
 	<li><strong>Notify your local Animal Control/Humane Society to report that you found a pet within 24 hours!  Link to a listing of all area shelters – </strong><strong><a href="http://www.indylostpetalert.com/shelters/">indylostpetalert.com/shelters/</a></strong></li>
 	<li><strong>Be aware of any local ordinances regarding the “rehoming of pets</strong>” – Marion County – Section 531-208 as us March 2, 2017– Lost and Stray Domestic Animals – states that “With the exception of the Humane Society of Indianapolis or other humane and/or breed rescue organizations recognized by the animal care services division, the finder will be considered the found animal’s owner for purposes of this chapter <strong>fourteen (14) continuous days</strong> after the found report was files with the animal care services division or its designee.” Hamilton County thirty (30) continuous days, Madison County seven (7) days, Boone County seven (7) days, &amp; Hendricks County seven (7) days. In simple terms, for Marion County, this means, “You <strong>cannot</strong> rehome the pet (unless the potential family understands that the owners have 14 days to claim it and that they must ACTIVELY try to find its family during that time).”</li>
 	<li>Review our LOST PET albums for a possible match to the pet you have found. Link to ILPA website: http://www.indylostpetalert.com/,  then click on LOST PETS.</li>
 	<li>Post lots of signs in the area or intersection where he/she was found, especially entrances/exits of your neighborhood, grocery stores, pet stores, and areas where people will see them. Neon signs really stand out! Not all people use social media so signs are important! Your sign can simply say, “Found Dog/Cat:  Call XXXX.”   Neon poster board from a dollar store makes for great signs!</li>
 	<li>Please share his/her alert on your Facebook Page and ask others to share also.  If you have a neighborhood or town Facebook Page or <a href="http://www.nextdoor.com/">nextdoor.com</a> site or email list, please get the word out about him/her using these methods also. It’s quite common that a found pet will belong to a family very nearby.</li>
 	<li><strong>Never assume that a pet is not loved based on appearance</strong>. You never know how long a pet has been missing. Animals who have been running for just two days without eating will drop weight quickly.</li>
 	<li>Please be very cautious of returning a pet to its potential owner. Ask for <strong>proof of ownership</strong>. Ask them for pictures, adoption records or vet records. Also ask them to describe the pet\'s collar or unique features.</li>
 	<li>BEWARE of SCAMMERS!  Although we detest this, we know there are dishonest people who peruse our site for dishonorable reasons.  Please DO NOT get involved with those who may dishonestly try to claim a pet as their own or offer to foster/buy the pet. These  contacts are illegal. If you suspect this, please contact us with the information communicated and the phone number used.  Local PD authorities will be involved.</li>
 	<li>When posting the found pet to other sites, never include the collar or harness, in the picture. You will see that we covered all of them.  Also, leave off details such as "not neutered", "appears pregnant" as that can draw predators.</li>
 	<li>There are a lot of "pet flippers" - people who will try to claim pets to simply turn around and sell them. Again, please require proof of ownership to prevent these people from getting the pet.</li>
 	<li>If there is ever a question about returning a pet to its owner, get Indianapolis Animal Care Services involved. Tell the potential owner that they can meet you at the shelter to claim their dog. (If you have any questions as to how to do this, let us know!)</li>
</ul>
<strong>Please notify us when you find the pet\'s family - we love happy reunion stories! You can email us at </strong><a href="mailto:ilpavolunteer@gmail.com"><strong>ilpavolunteer@gmail.com</strong></a><strong> or update on our website at </strong><a href="http://www.indylostpetalert.com/update-on-a-previously-reported-lost-or-found-pet/"><strong>http://www.indylostpetalert.com/update-on-a-previously-reported-lost-or-found-pet/</strong></a>

<strong>A copy of your submission is below:</strong>';
?>